In [1]:
import numpy as np

In [2]:
np.arange(1,21)
# this will give array from 1 to 20

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
np.zeros(3)              #this will give array with 3 zeros
np.zeros((2,3))          #this will give array with 2 rows and 3 coloums containg zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones(2)                 #this will return array with 2 ones
np.ones((2,3))             #this will reuturn matrix 2by 3 matrix with one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.linspace(0,5,10)        #this will return array of 10 elements from 0 to 5 with same difference in elements

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [6]:
np.eye(4)                   #this will return an identity matrix of 4 by 4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.random.rand(5,5)        #this will return an matrix containg random elements in 5 by 5 format

array([[0.1927416 , 0.28234675, 0.52100933, 0.22991665, 0.86543469],
       [0.15136709, 0.86724363, 0.93611036, 0.94817323, 0.3834213 ],
       [0.67175879, 0.20766349, 0.15872045, 0.44216228, 0.11037269],
       [0.05778706, 0.42544104, 0.35651693, 0.544444  , 0.31378268],
       [0.7808931 , 0.21523265, 0.60439011, 0.85221308, 0.77123748]])

In [8]:
np.random.random_integers(1,100)                    #this will return any random integer from 1 to 99 
np.random.random_integers(1,100,10)                 #this will return any 10 random interger from 1 to 99

/tmp/ipykernel_4190/3838268168.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  np.random.random_integers(1,100)                    #this will return any random integer from 1 to 99
/tmp/ipykernel_4190/3838268168.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  np.random.random_integers(1,100,10)                 #this will return any 10 random interger from 1 to 99


array([39, 48, 24,  1, 21, 33, 38, 49, 56, 22])

In [9]:
arrq = np.arange(1,26)
print(arrq)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [10]:
arrq.max()                                        #this will return the maximun value in the array
arrq.argmax()                                     #this will return the index number of maximun values (same with min)

24

In [11]:
arrq.reshape(5,5)                                 #this will convert the array into matrix of 5 by 5 as it contain 25 elements

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])