In [2]:
import numpy as np

In [5]:
np.arange(1,21)
# this will give array from 1 to 20

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [9]:
-np.zeros(3)              #this will give array with 3 zeros
np.zeros((2,3))          #this will give array with 2 rows and 3 coloums containg zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(2)                 #this will return array with 2 ones
np.ones((2,3))             #this will reuturn matrix 2by 3 matrix with one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(0,5,10)        #this will return array of 10 elements from 0 to 5 with same difference in elements

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.eye(4)                   #this will return an identity matrix of 4 by 4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5,5)        #this will return an matrix containg random elements in 5 by 5 format

array([[0.59352791, 0.29938886, 0.63049085, 0.05824303, 0.60184085],
       [0.40278823, 0.84734678, 0.65525921, 0.61406011, 0.38369498],
       [0.01773224, 0.28838673, 0.50042764, 0.70085086, 0.62462247],
       [0.6918614 , 0.99842994, 0.18742849, 0.61349903, 0.09221888],
       [0.10001592, 0.74713635, 0.489318  , 0.75631851, 0.33270579]])

In [20]:
np.random.random_integers(1,100)                    #this will return any random integer from 1 to 99 
np.random.random_integers(1,100,10)                 #this will return any 10 random interger from 1 to 99

/tmp/ipykernel_5134/539065264.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  np.random.random_integers(1,100)


59

In [32]:
arrq = np.arange(1,26)
print(arrq)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [46]:
arrq.max()                                        #this will return the maximun value in the array
arrq.argmax()                                     #this will return the index number of maximun values (same with min)

24

In [36]:
arrq.reshape(5,5)                                 #this will convert the array into matrix of 5 by 5 as it contain 25 elements

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])