In [1]:
import numpy as np

In [4]:
array = np.arange(1,31)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [5]:
array[9]                                         #this will return the number at 9th index
array[1:5]                                       #this will return the values form index 1 to index 4
array[8:]                                        #this will return the values from 8th index till the end 

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30])

In [6]:
array[0:5] = 15                                 #this will change the elements present at 0 to 4 th index to 15 
array                                           #here first elements from index 0 to 4 changes to 15

array([15, 15, 15, 15, 15,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [7]:
arr_mat = np.array([[1,2,3] ,[4,5,6] ,[7,8,9]])
arr_mat


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr_mat[1][2]                      #this will return the 2nd element in 1st row
# suppose i have to grab 7 i.e row index 2 and coloum index 0
arr_mat[2][0]        

7

In [14]:
# suppose we want a submatrix from a main matrix
arr_mat[:2,1:]

array([[2, 3],
       [5, 6]])

In [16]:
arr = np.arange(1,11)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
boolean_arr = arr > 5     
boolean_arr                              #this will give only values which are greater tha 5 in boolean format

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [19]:
# to get theri actual values 
arr[boolean_arr]

array([ 6,  7,  8,  9, 10])

In [20]:
#  or simple we can pass contion inside the brakcet
arr[arr >5]

array([ 6,  7,  8,  9, 10])