In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + arr                   #this will adds array i.e each elements doubled up

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr * arr                  #this will multiply each index with each index same as sum 

# we can also subtract

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [6]:
arr + 100                         
 #this will add the 10 to the each element in each elemnt in aaray , also subtract or multiply or divide

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [7]:
arr ** 2                   # this will give you squre of each element

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])